server:
  port: 10086

spring:
  application:
    name: Lottery
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.13:3306/fuse?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

python:
  exe-path: D:\dev\Python\Python39\python.exe

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

thread-pool:
  weather:
    core-size: 2
    max-size: 6
    queue-size: 300
    prefix: weather-Executor-
    keep-alive-seconds: 60